/* eslint camelcase: 0, max-len: 0 */

'use strict';

exports.seed = function(knex) {
  return knex('books').del()
    .then(() => {
      return knex('books').insert([{
        id: 1,
        title: 'Los detectives salvajes',
        subtitle: null,
        author: 'Roberto Bolaño',
        genre: 'fiction',
        language: 'Spanish',
        original_language: 'Spanish',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 2,
        title: 'The Secret History',
        subtitle: null,
        author: 'Donna Tartt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 3,
        title: 'The Sun Also Rises',
        subtitle: null,
        author: 'Ernest Hemingway',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1926,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 4,
        title: 'The Girls',
        subtitle: null,
        author: 'Emma Cline',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2016,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 5,
        title: 'The Amazing Adventures of Kavalier and Clay',
        subtitle: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 6,
        title: 'Cathedral',
        subtitle: null,
        author: 'Raymond Chandler',
        genre: 'short story',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 7,
        title: 'Guns, Germs, and Steel',
        subtitle: 'The Fates of Human Societies',
        author: 'Jared Diamond',
        genre: 'non-fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 8,
        title: 'War and Peace',
        subtitle: null,
        author: 'Leo Tolstoy',
        genre: 'fiction',
        language: 'English',
        original_language: 'Russian',
        publication_year: 1869,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 9,
        title: 'The Giving Tree',
        subtitle: null,
        author: 'Shel Silverstein',
        genre: 'juvenile fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1964,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 10,
        title: 'Philosophical Investigations',
        subtitle: null,
        author: 'Ludwig Wittgenstein',
        genre: 'philosophy',
        language: 'English',
        original_language: 'German',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 11,
        title: 'Dune',
        subtitle: null,
        author: 'Frank Herbert',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1965,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 12,
        title: 'Babel-17',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 13,
        title: 'Flowers for Algernon',
        subtitle: null,
        author: 'Daniel Keyes',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 14,
        title: 'The Einstein Intersection',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 15,
        title: 'Rite of Passage',
        subtitle: null,
        author: 'Alexei Panshin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 16,
        title: 'The Left Hand of Darkness',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 17,
        title: 'Ringworld',
        subtitle: null,
        author: 'Larry Niven',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 18,
        title: 'A Time of Changes',
        subtitle: null,
        author: 'Robert Silverberg',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 19,
        title: 'The Gods Themselves',
        subtitle: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 20,
        title: 'Rendezvous with Rama',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 21,
        title: 'The Dispossessed',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 22,
        title: 'The Forever War',
        subtitle: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 23,
        title: 'Man Plus',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 24,
        title: 'Gateway',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 25,
        title: 'Dreamsnake',
        subtitle: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 26,
        title: 'The Fountains of Paradise',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 27,
        title: 'Timescape',
        subtitle: null,
        author: 'Gregory Benford',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 28,
        title: 'The Claw of the Conciliator',
        subtitle: null,
        author: 'Gene Wolfe',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 29,
        title: 'No Enemy But Time',
        subtitle: null,
        author: 'Michael Bishop',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 30,
        title: 'Startide Rising',
        subtitle: null,
        author: 'David Brin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 31,
        title: 'Neuromancer',
        subtitle: null,
        author: 'William Gibson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 32,
        title: 'Ender\'s Game',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 33,
        title: 'Speaker for the Dead',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 34,
        title: 'The Falling Woman',
        subtitle: null,
        author: 'Pat Murphy',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 35,
        title: 'Falling Free',
        subtitle: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 36,
        title: 'The Healer\'s War',
        subtitle: null,
        author: 'Elizabeth Ann Scarborough',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 37,
        title: 'Tehanu',
        subtitle: 'The Last Book of Earthsea',
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 38,
        title: 'Stations of the Tide',
        subtitle: null,
        author: 'Michael Swanwick',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 39,
        title: 'Doomsday Book',
        subtitle: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 40,
        title: 'Red Mars',
        subtitle: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 41,
        title: 'Moving Mars',
        subtitle: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 42,
        title: 'The Terminal Experiment',
        subtitle: null,
        author: 'Robert J. Sawyer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 43,
        title: 'Slow River',
        subtitle: null,
        author: 'Nicola Griffith',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 44,
        title: 'The Moon and the Sun',
        subtitle: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 45,
        title: 'Forever Peace',
        subtitle: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 46,
        title: 'Parable of the Talents',
        subtitle: null,
        author: 'Octavia E. Butler',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 47,
        title: 'Darwin\'s Radio',
        subtitle: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 48,
        title: 'The Quantum Rose',
        subtitle: null,
        author: 'Catherine Asaro',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 49,
        title: 'American Gods',
        subtitle: null,
        author: 'Neil Gaiman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 50,
        title: 'The Speed of Dark',
        subtitle: null,
        author: 'Elizabeth Moon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 51,
        title: 'Paladin of Souls',
        subtitle: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 52,
        title: 'Camouflage',
        subtitle: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 53,
        title: 'Seeker',
        subtitle: null,
        author: 'Jack McDevitt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 54,
        title: 'The Yiddish Policeman\'s Union',
        subtitle: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 55,
        title: 'Powers',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 56,
        title: 'The Windup Girl',
        subtitle: null,
        author: 'Paolo Bacigalupi',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 57,
        title: 'Blackout/All Clear',
        subtitle: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 58,
        title: 'Among Others',
        subtitle: null,
        author: 'Jo Walton',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 59,
        title: '2312',
        subtitle: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 60,
        title: 'Ancillary Justice',
        subtitle: null,
        author: 'Ann Leckie',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 61,
        title: 'Annihilation',
        subtitle: null,
        author: 'Jeff VanderMeer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 62,
        title: 'Uprooted',
        subtitle: null,
        author: 'Naomi Novik',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      }]);
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('books_id_seq', (SELECT MAX(id) FROM books));"
      );
    });
};
