/* eslint camelcase: 0, max-len: 0 */

'use strict';

exports.seed = function(knex) {
  return knex('books').del()
    .then(() => {
      return knex('books').insert([{
        id: 1,
        title: 'Los detectives salvajes',
        subtitle: null,
        author: 'Roberto Bolaño',
        genre: 'fiction',
        language: 'Spanish',
        original_language: 'Spanish',
        publication_year: 1998,
        google_description: 'Arturo Belano y Ulises Lima, los detectives salvajes, salen a buscar las huellas de Cesrea Tinajero, la misteriosa escritora desaparecida en Mxico en los aos inmediatamente posteriores a la Revolucin, y esa bsqueda - el viaje y sus consecuencias - se prolonga durante veinte aos, desde 1976 hasta 1996, el tiempo cannico de cualquier errancia, bifurcndose a travs de mltiples personajes y continentes, en una novela en donde hay de todo: amores y muertes, asesinatos y fugas tursticas, manicomios y universidades, desapariciones y apariciones.Sus escenarios son Mxico, Nicaragua, Estados Unidos, Francia, Espaa, Austria, Israel, frica, siempre al comps de los detectives salvajes - poetas \'desperados\', traficantes ocasionales -, Arturo Belano y Ulises Lima, los enigmticos protagonistas de este libro que puede leerse como un refinadsimo thriller wellesiano, atravesado por un humor iconoclasta y feroz. Entre los personajes destaca un fotgrafo espaol en el ltimo escaln de la desesperacin, un neonazi borderline, un torero mexicano jubilado que vive en el desierto, una estudiante francesa lectora de Sade, una prostituta adolescente en permanente huida, una prcer uruguaya en el 68 latinoamericano, un abogado gallego herido por la poesa, un editor mexicano al que persiguen unos pistoleros a sueldo.Una novela extraordinaria en todos los sentidos, que confirma la deslumbrante calidad literaria de Roberto Bolao, un autor que ha sido reconocido por la crtica ms exigente como una de las grandes revelaciones de la literatura latinoamericana de los aos noventa.',
        google_image: '',
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 2,
        title: 'The Secret History',
        subtitle: null,
        author: 'Donna Tartt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 3,
        title: 'The Sun Also Rises',
        subtitle: null,
        author: 'Ernest Hemingway',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1926,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 4,
        title: 'The Girls',
        subtitle: null,
        author: 'Emma Cline',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2016,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 5,
        title: 'The Amazing Adventures of Kavalier and Clay',
        subtitle: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 6,
        title: 'Cathedral',
        subtitle: null,
        author: 'Raymond Chandler',
        genre: 'short story',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 7,
        title: 'Guns, Germs, and Steel',
        subtitle: 'The Fates of Human Societies',
        author: 'Jared Diamond',
        genre: 'non-fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 8,
        title: 'War and Peace',
        subtitle: null,
        author: 'Leo Tolstoy',
        genre: 'fiction',
        language: 'English',
        original_language: 'Russian',
        publication_year: 1869,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 9,
        title: 'The Giving Tree',
        subtitle: null,
        author: 'Shel Silverstein',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1964,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 10,
        title: 'Philosophical Investigations',
        subtitle: null,
        author: 'Ludwig Wittgenstein',
        genre: 'philosophy',
        language: 'English',
        original_language: 'German',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 11,
        title: 'Dune',
        subtitle: null,
        author: 'Frank Herbert',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1965,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 12,
        title: 'Babel-17',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1966,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 13,
        title: 'Flowers for Algernon',
        subtitle: null,
        author: 'Daniel Keyes',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1966,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 14,
        title: 'The Einstein Intersection',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1967,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 15,
        title: 'Rite of Passage',
        subtitle: null,
        author: 'Alexei Panshin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 16,
        title: 'The Left Hand of Darkness',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1969,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 17,
        title: 'Ringworld',
        subtitle: null,
        author: 'Larry Niven',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1970,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 18,
        title: 'A Time of Changes',
        subtitle: null,
        author: 'Robert Silverberg',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1971,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 19,
        title: 'The Gods Themselves',
        subtitle: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1972,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 20,
        title: 'Rendezvous with Rama',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1973,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 21,
        title: 'The Dispossessed',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1974,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 22,
        title: 'The Forever War',
        subtitle: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1974,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 23,
        title: 'Man Plus',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1976,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 24,
        title: 'Gateway',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 25,
        title: 'Dreamsnake',
        subtitle: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1978,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 26,
        title: 'The Fountains of Paradise',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1979,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 27,
        title: 'Timescape',
        subtitle: null,
        author: 'Gregory Benford',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1980,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 28,
        title: 'The Claw of the Conciliator',
        subtitle: null,
        author: 'Gene Wolfe',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1981,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 29,
        title: 'No Enemy But Time',
        subtitle: null,
        author: 'Michael Bishop',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1982,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 30,
        title: 'Startide Rising',
        subtitle: null,
        author: 'David Brin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 31,
        title: 'Neuromancer',
        subtitle: null,
        author: 'William Gibson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1984,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 32,
        title: 'Ender\'s Game',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1985,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 33,
        title: 'Speaker for the Dead',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1986,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 34,
        title: 'The Falling Woman',
        subtitle: null,
        author: 'Pat Murphy',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1986,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 35,
        title: 'Falling Free',
        subtitle: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1988,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 36,
        title: 'The Healer\'s War',
        subtitle: null,
        author: 'Elizabeth Ann Scarborough',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1988,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 37,
        title: 'Tehanu',
        subtitle: 'The Last Book of Earthsea',
        series: 'Earthsea',
        volume: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 38,
        title: 'Stations of the Tide',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Michael Swanwick',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 39,
        title: 'Doomsday Book',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 40,
        title: 'Red Mars',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 41,
        title: 'Moving Mars',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 42,
        title: 'The Terminal Experiment',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert J. Sawyer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 43,
        title: 'Slow River',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Nicola Griffith',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 44,
        title: 'The Moon and the Sun',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 45,
        title: 'Forever Peace',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 46,
        title: 'Parable of the Talents',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Octavia E. Butler',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 47,
        title: 'Darwin\'s Radio',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1999,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 48,
        title: 'The Quantum Rose',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Catherine Asaro',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 49,
        title: 'American Gods',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neil Gaiman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2001,
        google_description: 'The storm was coming.... Shadow spent three years in prison, keeping his head down, doing his time. All he wanted was to get back to the loving arms of his wife and to stay out of trouble for the rest of his life. But days before his scheduled release, he learns that his wife has been killed in an accident, and his world becomes a colder place. On the plane ride home to the funeral, Shadow meets a grizzled man who calls himself Mr. Wednesday. A self-styled grifter and rogue, Wednesday offers Shadow a job. And Shadow, a man with nothing to lose, accepts. But working for the enigmatic Wednesday is not without its price, and Shadow soon learns that his role in Wednesday\'s schemes will be far more dangerous than he ever could have imagined. Entangled in a world of secrets, he embarks on a wild road trip and encounters, among others, the murderous Czernobog, the impish Mr. Nancy, and the beautiful Easter -- all of whom seem to know more about Shadow than he himself does. Shadow will learn that the past does not die, that everyone, including his late wife, had secrets, and that the stakes are higher than anyone could have imagined. All around them a storm of epic proportions threatens to break. Soon Shadow and Wednesday will be swept up into a conflict as old as humanity itself. For beneath the placid surface of everyday life a war is being fought -- and the prize is the very soul of America. As unsettling as it is exhilarating, American Gods is a dark and kaleidoscopic journey deep into myth and across an America at once eerily familiar and utterly alien. Magnificently told, this work of literary magic will haunt the reader far beyond the final page.',
        google_image: 'http://books.google.com/books/content?id=Kasag4WdeM0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 50,
        title: 'Speed of Dark',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Elizabeth Moon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2002,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 51,
        title: 'Paladin of Souls',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 52,
        title: 'Camouflage',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2004,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 53,
        title: 'Seeker',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jack McDevitt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 54,
        title: 'The Yiddish Policeman\'s Union',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 55,
        title: 'Powers',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 56,
        title: 'The Windup Girl',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Paolo Bacigalupi',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2009,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 57,
        title: 'Blackout/All Clear',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2010,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 58,
        title: 'Among Others',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jo Walton',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2011,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 59,
        title: '2312',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2012,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 60,
        title: 'Ancillary Justice',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ann Leckie',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2013,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 61,
        title: 'Annihilation',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jeff VanderMeer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2014,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 62,
        title: 'Uprooted',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Naomi Novik',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2015,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 63,
        title: 'The Fellowship of the Ring',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 1,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1954,
        google_description: 'The first volume in J.R.R. Tolkien\'s epic adventure THE LORD OF THE RINGS One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose. “A unique, wholly realized other world, evoked from deep in the well of Time, massively detailed, absorbingly entertaining, profound in meaning.” – New York Times',
        google_image: 'http://books.google.com/books/content?id=aWZzLPhY4o0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 64,
        title: 'The Two Towers',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 2,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1954,
        google_description: 'The second volume in J.R.R. Tolkien\'s epic adventure THE LORD OF THE RINGS One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go. “Among the greatest works of imaginative fiction of the twentieth century. The book presents us with the richest profusion of new lands and creatures, from the beauty of Lothlórien to the horror of Mordor.” – Sunday Telegraph',
        google_image: 'http://books.google.com/books/content?id=12e8PJ2T7sQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 65,
        title: 'The Return of the King',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 3,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1955,
        google_description: 'Concluding the story of The Hobbit, this is the final part of Tolkien\'s epic master piece. Impossible to describe in a few words, JRR Tolkien’s great work of imaginative fiction has been labelled both a heroic romance and a classic fantasy fiction. By turns comic and homely, epic and diabolic, the narrative moves through countless changes of scene and character in an imaginary world which is totally convincing in its detail. Tolkien created a vast new mythology in an invented world which has proved timeless in its appeal.',
        google_image: 'http://books.google.com/books/content?id=a2uGDAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 66,
        title: 'The Hitchhiker\'s Guide to the Galaxy',
        subtitle: null,
        series: 'The Hitchhiker\'s Guide to the Galaxy',
        volume: 1,
        author: 'Douglas Adams',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1979,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 67,
        title: 'A Game of Thrones',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 1,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 68,
        title: 'A Clash of Kings',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 2,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 69,
        title: 'A Storm of Storms',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 3,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 70,
        title: 'A Feast for Crows',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 4,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 71,
        title: 'A Dance with Dragons',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 5,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2011,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 72,
        title: 'Nineteen Eighty-Four',
        subtitle: null,
        series: null,
        volume: null,
        author: 'George Orwell',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1949,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 73,
        title: 'Fahrenheit 451',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ray Bradbury',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 74,
        title: 'Foundation',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 1,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1951,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 75,
        title: 'Foundation and Empire',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 2,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1952,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 76,
        title: 'Second Foundation',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 3,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 77,
        title: 'Brave New World',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Aldous Huxley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1932,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 78,
        title: 'The Princess Bride',
        subtitle: null,
        series: null,
        volume: null,
        author: 'William Goldman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1973,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 79,
        title: 'The Eye of the World',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 1,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 80,
        title: 'The Great Hunt',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 2,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 81,
        title: 'The Dragon Reborn',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 3,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 82,
        title: 'The Shadow Rising',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 4,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 83,
        title: 'The Fires of Heaven',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 5,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 84,
        title: 'Lord of Chaos',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 6,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1994,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 85,
        title: 'A Crown of Swords',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 7,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 86,
        title: 'The Path of Daggers',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 8,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 87,
        title: 'Winter\'s Heart',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 9,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 88,
        title: 'Crossroads of Twilight',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 10,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 89,
        title: 'Knife of Dreams',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 11,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 90,
        title: 'The Gathering Storm',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 12,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2009,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 91,
        title: 'Towers of Midnight',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 13,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2010,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 92,
        title: 'A Memory of Light',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 14,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2013,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 93,
        title: 'Animal Farm',
        subtitle: null,
        series: null,
        volume: null,
        author: 'George Orwell',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1945,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 94,
        title: 'Watchmen',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Alan Moore, Dave Gibbons',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1987,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 95,
        title: 'I, Robot',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1950,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 96,
        title: 'Stranger in a Strange Land',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert A. Heinlein',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1961,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 97,
        title: 'The Name of the Wind',
        subtitle: null,
        series: 'The Kingkiller Chronicle',
        volume: 1,
        author: 'Patrick Rothfuss',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 98,
        title: 'The Wise Man\'s Fear',
        subtitle: null,
        series: 'The Kingkiller Chronicle',
        volume: 2,
        author: 'Patrick Rothfuss',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2011,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 99,
        title: 'Slaughterhouse-Five',
        subtitle: 'or The Children\'s Crusade: A Duty-Dance with Death',
        series: null,
        volume: null,
        author: 'Kurt Vonnegut',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1969,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 100,
        title: 'Frankenstein',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Mary Shelley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1818,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 101,
        title: 'Do Androids Dream of Electric Sheep?',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Philip K. Dick',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 102,
        title: 'The Handmaid\'s Tale',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Margaret Atwood',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1985,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 103,
        title: 'The Gunslinger',
        subtitle: null,
        series: 'The Dark Tower',
        volume: 1,
        author: 'Stephen King',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1982,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 104,
        title: '2001',
        subtitle: 'A Space Odyssey',
        series: null,
        volume: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 105,
        title: 'The Stand',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Stephen King',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1978,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 106,
        title: 'Snow Crash',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neal Stephenson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 107,
        title: 'The Martian Chronicles',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ray Bradbury',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1950,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 108,
        title: 'Cat\'s Cradle',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Kurt Vonnegut',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1963,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 109,
        title: 'The Sandman',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neil Gaiman',
        genre: 'graphic novel',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 110,
        title: 'A Clockwork Orange',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Anthony Burgess',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1962,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 111,
        title: 'Starship Troopers',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert A. Heinlein',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1959,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 112,
        title: 'Watership Down',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Richard Adams',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1972,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 113,
        title: 'Dragonflight',
        subtitle: null,
        series: 'Dragonriders of Pern',
        volume: 1,
        author: 'Anne McCaffrey',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 114,
        title: 'The Moon is a Harsh Mistress',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert A. Heinlein',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1966,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 115,
        title: 'A Canticle for Leibowitz',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Walter M. Miller Jr.',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1960,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 116,
        title: 'The Time Machine',
        subtitle: null,
        series: null,
        volume: null,
        author: 'H.G. Wells',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1895,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 117,
        title: '20,000 Leagues Under the Sea',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jules Verne',
        genre: 'fiction',
        language: 'English',
        original_language: 'French',
        publication_year: 1870,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 118,
        title: 'The War of the Worlds',
        subtitle: null,
        series: null,
        volume: null,
        author: 'H.G. Wells',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1898,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 119,
        title: 'Nine Princes in Amber',
        subtitle: null,
        series: 'Chronicles of Amber',
        volume: 1,
        author: 'Roger Zelazny',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1970,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 120,
        title: 'Pawn of Prophecy',
        subtitle: null,
        series: 'The Belgariad',
        volume: 1,
        author: 'David Eddings',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1982,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 121,
        title: 'The Mists of Avalon',
        subtitle: null,
        series: 'Avalon',
        volume: 1,
        author: 'Marion Zimmer Bradley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 122,
        title: 'Mistborn: The Final Empire',
        subtitle: null,
        series: 'Mistborn',
        volume: 1,
        author: 'Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2006,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 123,
        title: 'The Silmarillion',
        subtitle: null,
        series: null,
        volume: null,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 124,
        title: 'The Once and Future King',
        subtitle: null,
        series: null,
        volume: null,
        author: 'T.H. White',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1958,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 125,
        title: 'Neverwhere',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neil Gaiman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 126,
        title: 'Childhood\'s End',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 127,
        title: 'Contact',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Carl Sagan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1985,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 128,
        title: 'Hyperion',
        subtitle: null,
        series: 'Hyperion Cantos',
        volume: 1,
        author: 'Dan Simmons',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1989,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 129,
        title: 'Stardust',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neil Gaiman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1999,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 130,
        title: 'Cryptonomicon',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neal Stephenson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1999,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 131,
        title: 'World War Z',
        subtitle: 'An Oral History of the Zombie War',
        series: null,
        volume: null,
        author: 'Max Brooks',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2006,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 132,
        title: 'The Last Unicorn',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Peter S. Beagle',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 133,
        title: 'Small Gods',
        subtitle: null,
        series: 'Discworld',
        volume: 13,
        author: 'Terry Pratchett',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 134,
        title: 'Lord Foul\'s Bane',
        subtitle: null,
        series: 'The Chronicles of Thomas Covenant',
        volume: 1,
        author: 'Stephen R. Donaldson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 135,
        title: 'Shards of Honor',
        subtitle: null,
        series: 'The Vorkosigan Saga',
        volume: 1,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1986,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 136,
        title: 'Going Postal',
        subtitle: null,
        series: 'Discworld',
        volume: 33,
        author: 'Terry Pratchett',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2004,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 137,
        title: 'The Mote in God\'s Eye',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Larry Niven, Jerry Pournelle',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1974,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 138,
        title: 'Wizard\'s First Rule',
        subtitle: null,
        series: 'The Sword of Truth',
        volume: 1,
        author: 'Terry Goodkind',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1994,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 139,
        title: 'The Road',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Cormac McCarthy',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2006,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 140,
        title: 'Jonathan Strange & Mr. Norrell',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Susanna Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2004,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 141,
        title: 'Old Man\'s War',
        subtitle: null,
        series: 'Old Man\'s War',
        volume: 1,
        author: 'John Scalzi',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 142,
        title: 'I Am Legend',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Richard Matheson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1954,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 143,
        title: 'Magician',
        subtitle: null,
        series: 'The Riftwar Saga',
        volume: 1,
        author: 'Raymond E. Feist',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1982,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 144,
        title: 'The Sword of Shannara',
        subtitle: null,
        series: 'Shannara',
        volume: 1,
        author: 'Terry Brooks',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 145,
        title: 'The Coming of Conan',
        subtitle: null,
        series: 'Conan the Barbarian',
        volume: 1,
        author: 'Robert E. Howard',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 146,
        title: 'Assassin\'s Apprentice',
        subtitle: null,
        series: 'Farseer Trilogy',
        volume: 1,
        author: 'Robin Hobb',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 147,
        title: 'The Time Traveler\'s Wife',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Audrey Niffenegger',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 148,
        title: 'The Way of Kings',
        subtitle: null,
        series: 'The Stormlight Archive',
        volume: 1,
        author: 'Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2010,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 149,
        title: 'Journey to the Center of the Earth',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jules Verne',
        genre: 'fiction',
        language: 'English',
        original_language: 'French',
        publication_year: 1864,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 150,
        title: 'Homeland',
        subtitle: null,
        series: 'The Dark Elf Trilogy',
        volume: 1,
        author: 'R.A. Salvatore',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 151,
        title: 'The Diamond Age',
        subtitle: 'Or, A Young Lady\'s Illustrated Primer',
        series: null,
        volume: null,
        author: 'Neal Stephenson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 152,
        title: 'Kushiel\'s Dart',
        subtitle: null,
        series: 'Kushiel\'s Legacy',
        volume: 1,
        author: 'Jacqueline Carey',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2001,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 153,
        title: 'Something Wicked This Way Comes',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ray Bradbury',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1962,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 154,
        title: 'Wicked',
        subtitle: 'The Life and Times of the Wicked Witch of the West',
        series: 'The Wicked Years',
        volume: 1,
        author: 'Gregory Maguire',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 155,
        title: 'Gardens of the Moon',
        subtitle: null,
        series: 'Malazan Book of the Fallen',
        volume: 1,
        author: 'Steven Erikson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1999,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 156,
        title: 'The Eyre Affair',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jasper Fforde',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2001,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 157,
        title: 'Consider Phlebas',
        subtitle: null,
        series: 'The Culture',
        volume: 1,
        author: 'Iain M. Banks',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1987,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 158,
        title: 'The Crystal Cave',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Mary Stewart',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1970,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 159,
        title: 'Anathem',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neal Stephenson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2008,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 160,
        title: 'Furies of Calderon',
        subtitle: null,
        series: 'Codex Alera',
        volume: 1,
        author: 'Jim Butcher',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2004,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 161,
        title: 'The Shadow of the Torturer',
        subtitle: null,
        series: 'The Book of the New Sun',
        volume: 1,
        author: 'Gene Wolfe',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1980,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 162,
        title: 'Heir to the Empire',
        subtitle: null,
        series: 'The Thrawn Trilogy',
        volume: 1,
        author: 'Timothy Zahn',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 163,
        title: 'Outlander',
        subtitle: null,
        series: 'Outlander Series',
        volume: 1,
        author: 'Diana Gabaldon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 164,
        title: 'Elric of Melniboné',
        subtitle: null,
        series: 'The Elric Saga',
        volume: 1,
        author: 'Michael Moorcock',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1972,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 165,
        title: 'The Illustrated Man',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ray Bradbury',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1951,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 166,
        title: 'Sunshine',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robin McKinley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 167,
        title: 'A Fire Upon the Deep',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Vernor Vinge',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 168,
        title: 'The Caves of Steel',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1954,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 169,
        title: 'Lucifer\'s Hammer',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Larry Niven, Jerry Pournelle',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 170,
        title: 'Perdido Street Station',
        subtitle: null,
        series: null,
        volume: null,
        author: 'China Miéville',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 171,
        title: 'A Spell for Chameleon',
        subtitle: null,
        series: 'Xanth',
        volume: 1,
        author: 'Piers Anthony',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 172,
        title: 'Out of the Silent Planet',
        subtitle: null,
        series: 'The Space Trilogy',
        volume: 1,
        author: 'C.S. Lewis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1938,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      }]);
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('books_id_seq', (SELECT MAX(id) FROM books));"
      );
    });
};
