/* eslint camelcase: 0, max-len: 0 */

'use strict';

exports.seed = function(knex) {
  return knex('books').del()
    .then(() => {
      return knex('books').insert([{
        id: 1,
        title: 'Los detectives salvajes',
        subtitle: null,
        author: 'Roberto Bolaño',
        genre: 'fiction',
        language: 'Spanish',
        original_language: 'Spanish',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 2,
        title: 'The Secret History',
        subtitle: null,
        author: 'Donna Tartt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 3,
        title: 'The Sun Also Rises',
        subtitle: null,
        author: 'Ernest Hemingway',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1926,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 4,
        title: 'The Girls',
        subtitle: null,
        author: 'Emma Cline',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2016,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 5,
        title: 'The Amazing Adventures of Kavalier and Clay',
        subtitle: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 6,
        title: 'Cathedral',
        subtitle: null,
        author: 'Raymond Chandler',
        genre: 'short story',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 7,
        title: 'Guns, Germs, and Steel',
        subtitle: 'The Fates of Human Societies',
        author: 'Jared Diamond',
        genre: 'non-fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 8,
        title: 'War and Peace',
        subtitle: null,
        author: 'Leo Tolstoy',
        genre: 'fiction',
        language: 'English',
        original_language: 'Russian',
        publication_year: 1869,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 9,
        title: 'The Giving Tree',
        subtitle: null,
        author: 'Shel Silverstein',
        genre: 'juvenile fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1964,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 10,
        title: 'Philosophical Investigations',
        subtitle: null,
        author: 'Ludwig Wittgenstein',
        genre: 'philosophy',
        language: 'English',
        original_language: 'German',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 11,
        title: 'Dune',
        subtitle: null,
        author: 'Frank Herbert',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1965,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 12,
        title: 'Babel-17',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1966,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 13,
        title: 'Flowers for Algernon',
        subtitle: null,
        author: 'Daniel Keyes',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1966,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 14,
        title: 'The Einstein Intersection',
        subtitle: null,
        author: 'Samuel R. Delany',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1967,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 15,
        title: 'Rite of Passage',
        subtitle: null,
        author: 'Alexei Panshin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 16,
        title: 'The Left Hand of Darkness',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1969,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 17,
        title: 'Ringworld',
        subtitle: null,
        author: 'Larry Niven',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1970,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 18,
        title: 'A Time of Changes',
        subtitle: null,
        author: 'Robert Silverberg',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1971,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 19,
        title: 'The Gods Themselves',
        subtitle: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1972,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 20,
        title: 'Rendezvous with Rama',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1973,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 21,
        title: 'The Dispossessed',
        subtitle: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1974,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 22,
        title: 'The Forever War',
        subtitle: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1974,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 23,
        title: 'Man Plus',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1976,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 24,
        title: 'Gateway',
        subtitle: null,
        author: 'Frederik Pohl',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1977,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 25,
        title: 'Dreamsnake',
        subtitle: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1978,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 26,
        title: 'The Fountains of Paradise',
        subtitle: null,
        author: 'Arthur C. Clarke',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1979,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 27,
        title: 'Timescape',
        subtitle: null,
        author: 'Gregory Benford',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1980,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 28,
        title: 'The Claw of the Conciliator',
        subtitle: null,
        author: 'Gene Wolfe',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1981,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 29,
        title: 'No Enemy But Time',
        subtitle: null,
        author: 'Michael Bishop',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1982,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 30,
        title: 'Startide Rising',
        subtitle: null,
        author: 'David Brin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1983,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 31,
        title: 'Neuromancer',
        subtitle: null,
        author: 'William Gibson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1984,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 32,
        title: 'Ender\'s Game',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1985,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 33,
        title: 'Speaker for the Dead',
        subtitle: null,
        author: 'Orson Scott Card',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1986,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 34,
        title: 'The Falling Woman',
        subtitle: null,
        author: 'Pat Murphy',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1986,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 35,
        title: 'Falling Free',
        subtitle: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1988,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 36,
        title: 'The Healer\'s War',
        subtitle: null,
        author: 'Elizabeth Ann Scarborough',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1988,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 37,
        title: 'Tehanu',
        subtitle: 'The Last Book of Earthsea',
        series: 'Earthsea',
        volume: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 38,
        title: 'Stations of the Tide',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Michael Swanwick',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 39,
        title: 'Doomsday Book',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 40,
        title: 'Red Mars',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 41,
        title: 'Moving Mars',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 42,
        title: 'The Terminal Experiment',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert J. Sawyer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 43,
        title: 'Slow River',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Nicola Griffith',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1995,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 44,
        title: 'The Moon and the Sun',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Vonda N. McIntyre',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 45,
        title: 'Forever Peace',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1997,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 46,
        title: 'Parable of the Talents',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Octavia E. Butler',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 47,
        title: 'Darwin\'s Radio',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Greg Bear',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1999,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 48,
        title: 'The Quantum Rose',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Catherine Asaro',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 49,
        title: 'American Gods',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Neil Gaiman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2001,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 50,
        title: 'Speed of Dark',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Elizabeth Moon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2002,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 51,
        title: 'Paladin of Souls',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Lois McMaster Bujold',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 52,
        title: 'Camouflage',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Joe Haldeman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2004,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 53,
        title: 'Seeker',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jack McDevitt',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 54,
        title: 'The Yiddish Policeman\'s Union',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Michael Chabon',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 55,
        title: 'Powers',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ursula K. Le Guin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 56,
        title: 'The Windup Girl',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Paolo Bacigalupi',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2009,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 57,
        title: 'Blackout/All Clear',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Connie Willis',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2010,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 58,
        title: 'Among Others',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jo Walton',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2011,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 59,
        title: '2312',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Kim Stanley Robinson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2012,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 60,
        title: 'Ancillary Justice',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ann Leckie',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2013,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 61,
        title: 'Annihilation',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Jeff VanderMeer',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2014,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 62,
        title: 'Uprooted',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Naomi Novik',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2015,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 63,
        title: 'The Fellowship of the Ring',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 1,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 64,
        title: 'The Two Towers',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 2,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 65,
        title: 'The Return of the King',
        subtitle: null,
        series: 'The Lord of the Rings',
        volume: 3,
        author: 'J.R.R. Tolkien',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 66,
        title: 'The Hitchhiker\'s Guide to the Galaxy',
        subtitle: null,
        series: 'The Hitchhiker\'s Guide to the Galaxy',
        volume: 1,
        author: 'Douglas Adams',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 67,
        title: 'A Game of Thrones',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 1,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 68,
        title: 'A Clash of Kings',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 2,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 69,
        title: 'A Storm of Storms',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 3,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 70,
        title: 'A Feast for Crows',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 4,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 71,
        title: 'A Dance with Dragons',
        subtitle: null,
        series: 'A Song of Ice and Fire',
        volume: 5,
        author: 'George R.R. Martin',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 72,
        title: '1984',
        subtitle: null,
        series: null,
        volume: null,
        author: 'George Orwell',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 73,
        title: 'Fahrenheit 451',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Ray Bradbury',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: null,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 74,
        title: 'Foundation',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 1,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1951,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 75,
        title: 'Foundation and Empire',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 2,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1952,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 76,
        title: 'Second Foundation',
        subtitle: null,
        series: 'Foundation Trilogy',
        volume: 3,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1953,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 77,
        title: 'Brave New World',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Aldous Huxley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1932,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 78,
        title: 'The Princess Bride',
        subtitle: null,
        series: null,
        volume: null,
        author: 'William Goldman',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1973,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 79,
        title: 'The Eye of the World',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 1,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 80,
        title: 'The Great Hunt',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 2,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1990,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 81,
        title: 'The Dragon Reborn',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 3,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1991,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 82,
        title: 'The Shadow Rising',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 4,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1992,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 83,
        title: 'The Fires of Heaven',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 5,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1993,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 84,
        title: 'Lord of Chaos',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 6,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1994,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 85,
        title: 'A Crown of Swords',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 7,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1996,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 86,
        title: 'The Path of Daggers',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 8,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1998,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 87,
        title: 'Winter\'s Heart',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 9,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2000,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 88,
        title: 'Crossroads of Twilight',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 10,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2003,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 89,
        title: 'Knife of Dreams',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 11,
        author: 'Robert Jordan',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2005,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 90,
        title: 'The Gathering Storm',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 12,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2009,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 91,
        title: 'Towers of Midnight',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 13,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2010,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 92,
        title: 'A Memory of Light',
        subtitle: null,
        series: 'The Wheel of Time',
        volume: 14,
        author: 'Robert Jordan, Brandon Sanderson',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2013,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 93,
        title: 'Animal Farm',
        subtitle: null,
        series: null,
        volume: null,
        author: 'George Orwell',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1945,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 94,
        title: 'Watchmen',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Alan Moore, Dave Gibbons',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1987,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 95,
        title: 'I, Robot',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Isaac Asimov',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1950,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 96,
        title: 'Stranger in a Strange Land',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Robert A. Heinlein',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1961,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 97,
        title: 'The Name of the Wind',
        subtitle: null,
        series: 'The Kingkiller Chronicle',
        volume: 1,
        author: 'Patrick Rothfuss',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2007,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 98,
        title: 'The Wise Man\'s Fear',
        subtitle: null,
        series: 'The Kingkiller Chronicle',
        volume: 2,
        author: 'Patrick Rothfuss',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 2011,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 99,
        title: 'Slaughterhouse-Five',
        subtitle: 'or The Children\'s Crusade: A Duty-Dance with Death',
        series: null,
        volume: null,
        author: 'Kurt Vonnegut',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1969,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 100,
        title: 'Frankenstein',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Mary Shelley',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1818,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 101,
        title: 'Do Androids Dream of Electric Sheep?',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Philip K. Dick',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1968,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      },
      {
        id: 102,
        title: 'The Handmaid\'s Tale',
        subtitle: null,
        series: null,
        volume: null,
        author: 'Margaret Atwood',
        genre: 'fiction',
        language: 'English',
        original_language: 'English',
        publication_year: 1985,
        created_at: new Date('2016-12-07 16:17:12 UTC'),
        updated_at: new Date('2016-12-07 16:17:12 UTC')
      }]);
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('books_id_seq', (SELECT MAX(id) FROM books));"
      );
    });
};
